dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  share_plus: ^7.2.1
  # Pour le serveur et les mises à jour
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.3
  package_info_plus: ^5.0.1 # Pour détecter la version actuelle
